services:
  postgres:
    image: postgres:16
    container_name: mediscanflow-postgres
    environment:
      POSTGRES_DB: mediscanflow
      POSTGRES_USER: mediscanflow
      POSTGRES_PASSWORD: mediscanflow
    ports:
      - "5432:5432"
    volumes:
      - mediscanflow-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mediscanflow-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: mediscanflow
      RABBITMQ_DEFAULT_PASS: mediscanflow
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - mediscanflow-rabbitmq-data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    container_name: mediscanflow-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mediscanflow
      MINIO_ROOT_PASSWORD: mediscanflow123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - mediscanflow-minio-data:/data

  medical-platform-service:
    build:
      context: ../services/medical-platform-service
      dockerfile: Dockerfile
    container_name: mediscanflow-medical-platform-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mediscanflow
      SPRING_DATASOURCE_USERNAME: mediscanflow
      SPRING_DATASOURCE_PASSWORD: mediscanflow

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: mediscanflow
      SPRING_RABBITMQ_PASSWORD: mediscanflow

      APP_STORAGE_MINIO_ENDPOINT: http://minio:9000
      APP_STORAGE_MINIO_PUBLIC_ENDPOINT: http://localhost:9000
      APP_STORAGE_MINIO_ACCESS_KEY: mediscanflow
      APP_STORAGE_MINIO_SECRET_KEY: mediscanflow123
      APP_STORAGE_MINIO_BUCKET: medical-scans
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
      - minio

  ai-inference-service:
    build:
      context: ../services/ai-inference-service
      dockerfile: Dockerfile
    container_name: mediscanflow-ai-inference-service
    restart: unless-stopped
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: mediscanflow
      RABBITMQ_PASSWORD: mediscanflow

      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: mediscanflow
      MINIO_SECRET_KEY: mediscanflow123
      MINIO_BUCKET: medical-scans
      MINIO_SECURE: false

      MODEL_PATH: models/yolov8n-brain-tumor.pt
      YOLO_CONFIDENCE_THRESHOLD: 0.25
      SIMULATE_INFERENCE_FAILURE: false
      YOLO_CONFIG_DIR: /tmp/Ultralytics
    volumes:
      - ../services/ai-inference-service/models:/app/models:ro
    depends_on:
      - rabbitmq
      - minio

volumes:
  mediscanflow-postgres-data:
  mediscanflow-rabbitmq-data:
  mediscanflow-minio-data:
