package com.chrisitstyle.mediscanflow.medicalplatform.analyses.report;

import com.chrisitstyle.mediscanflow.medicalplatform.analyses.Analysis;
import com.chrisitstyle.mediscanflow.medicalplatform.analyses.AnalysisDetection;
import com.chrisitstyle.mediscanflow.medicalplatform.analyses.AnalysisStatus;
import org.openpdf.text.*;
import org.openpdf.text.Rectangle;
import org.openpdf.text.pdf.PdfPCell;
import org.openpdf.text.pdf.PdfPTable;
import org.springframework.stereotype.Component;

import java.awt.*;
import java.time.Instant;
import java.util.List;

import static com.chrisitstyle.mediscanflow.medicalplatform.analyses.report.AnalysisReportStyles.*;

@Component
class AnalysisReportSectionRenderer {

    private static final String AI_RESULT_TITLE = "AI result";

    private final AnalysisReportTableFactory tableFactory;
    private final AnalysisReportImageFactory imageFactory;

    AnalysisReportSectionRenderer(
            AnalysisReportTableFactory tableFactory,
            AnalysisReportImageFactory imageFactory
    ) {
        this.tableFactory = tableFactory;
        this.imageFactory = imageFactory;
    }

    void addHeader(Document document, Analysis analysis) throws DocumentException {
        PdfPTable headerTable = createHeaderTable();

        headerTable.addCell(createHeaderLeftCell(analysis));
        headerTable.addCell(createHeaderRightCell(analysis.getStatus()));

        document.add(headerTable);
    }

    void addOverviewSection(Document document, Analysis analysis) throws DocumentException {
        PdfPTable overviewTable = new PdfPTable(2);
        overviewTable.setWidthPercentage(100);
        overviewTable.setWidths(new float[]{1, 1});
        overviewTable.setSpacingAfter(16);

        overviewTable.addCell(tableFactory.createInfoCard(
                "Patient",
                tableFactory.createPatientTable(analysis.getPatient())
        ));

        overviewTable.addCell(tableFactory.createInfoCard(
                "Analysis",
                tableFactory.createAnalysisTable(analysis)
        ));

        document.add(overviewTable);
    }

    void addImagesSection(Document document, Analysis analysis) throws DocumentException {
        addSectionTitle(document, "Images");

        PdfPTable imageTable = new PdfPTable(2);
        imageTable.setWidthPercentage(100);
        imageTable.setWidths(new float[]{1, 1});
        imageTable.setSpacingAfter(16);

        imageTable.addCell(imageFactory.createImageCard("Original scan", analysis.getObjectKey()));

        if (analysis.getResultObjectKey() == null || analysis.getResultObjectKey().isBlank()) {
            imageTable.addCell(imageFactory.createPlaceholderImageCard(
                    AI_RESULT_TITLE,
                    "AI result image is not available yet."
            ));
        } else {
            imageTable.addCell(imageFactory.createImageCard(
                    AI_RESULT_TITLE,
                    analysis.getResultObjectKey()
            ));
        }

        document.add(imageTable);
    }

    void addDetectionsSection(
            Document document,
            List<AnalysisDetection> detections
    ) throws DocumentException {
        addSectionTitle(document, "Detections");

        if (detections == null || detections.isEmpty()) {
            document.add(tableFactory.createNoDetectionsTable());
            return;
        }

        document.add(tableFactory.createDetectionsTable(detections));
    }

    void addFooter(Document document) throws DocumentException {
        PdfPTable footerTable = new PdfPTable(1);
        footerTable.setWidthPercentage(100);
        footerTable.setSpacingBefore(8);

        String generatedAt = DATE_TIME_FORMATTER.format(Instant.now());

        PdfPCell footerCell = new PdfPCell(new Phrase(
                "Generated by MediScanFlow on " + generatedAt + ". This report was created automatically from stored analysis data.",
                FOOTER_FONT
        ));
        footerCell.setBorder(Rectangle.TOP);
        footerCell.setBorderColor(BORDER);
        footerCell.setPaddingTop(10);

        footerTable.addCell(footerCell);
        document.add(footerTable);
    }

    private PdfPTable createHeaderTable() throws DocumentException {
        PdfPTable headerTable = new PdfPTable(2);
        headerTable.setWidthPercentage(100);
        headerTable.setWidths(new float[]{4.2F, 1.2F});
        headerTable.setSpacingAfter(18);

        return headerTable;
    }

    private PdfPCell createHeaderLeftCell(Analysis analysis) {
        PdfPCell leftCell = new PdfPCell();
        leftCell.setBorder(Rectangle.NO_BORDER);
        leftCell.setPadding(0);

        Paragraph title = new Paragraph("MediScanFlow Analysis Report", TITLE_FONT);
        title.setSpacingAfter(6);
        leftCell.addElement(title);

        Paragraph subtitle = new Paragraph(
                "Generated automatically from the AI medical scan workflow.",
                SUBTITLE_FONT
        );
        subtitle.setSpacingAfter(8);
        leftCell.addElement(subtitle);

        Paragraph analysisId = new Paragraph("Analysis ID: " + analysis.getId(), SUBTITLE_FONT);
        leftCell.addElement(analysisId);

        return leftCell;
    }

    private PdfPCell createHeaderRightCell(AnalysisStatus status) {
        PdfPCell rightCell = new PdfPCell();
        rightCell.setBorder(Rectangle.NO_BORDER);
        rightCell.setPaddingTop(4);
        rightCell.setHorizontalAlignment(Element.ALIGN_RIGHT);

        PdfPTable badgeTable = new PdfPTable(1);
        badgeTable.setWidthPercentage(100);
        badgeTable.addCell(createStatusBadgeCell(status));
        rightCell.addElement(badgeTable);

        return rightCell;
    }

    private PdfPCell createStatusBadgeCell(AnalysisStatus status) {
        PdfPCell cell = new PdfPCell(new Phrase(status.name(), STATUS_FONT));
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setBackgroundColor(getStatusColor(status));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        cell.setPaddingTop(6);
        cell.setPaddingBottom(6);

        return cell;
    }

    private void addSectionTitle(Document document, String title) throws DocumentException {
        Paragraph sectionTitle = new Paragraph(title, SECTION_FONT);
        sectionTitle.setSpacingBefore(4);
        sectionTitle.setSpacingAfter(8);

        document.add(sectionTitle);
    }

    private Color getStatusColor(AnalysisStatus status) {
        return switch (status) {
            case COMPLETED -> SUCCESS;
            case FAILED -> DANGER;
            case QUEUED -> WARNING;
            case PROCESSING -> PRIMARY;
            case UPLOADED -> NEUTRAL;
        };
    }
}